In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data/stevenhan_move_level.csv')

In [3]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,...,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move
0,WGJV5DRb,1,white,stevenhan,c4,10+5,5,60003.0,600.03,-3.0,...,1,1,0,0,1,0,0,0,0,0
1,WGJV5DRb,1,black,Mein_letzter_Flug,Nf6,10+5,5,60003.0,600.03,-3.0,...,1,1,0,0,0,1,0,0,0,0
2,WGJV5DRb,2,white,stevenhan,Nc3,10+5,5,60179.0,601.79,-176.0,...,1,1,0,0,0,1,0,0,0,0
3,WGJV5DRb,2,black,Mein_letzter_Flug,e6,10+5,5,56907.0,569.07,3096.0,...,1,1,0,0,1,0,0,0,0,0
4,WGJV5DRb,3,white,stevenhan,g3,10+5,5,59891.0,598.91,288.0,...,1,1,0,0,1,0,0,0,0,0

In [4]:
df.shape

(6710, 40)

In [5]:
# Filter to only have my games:
df = df[df['username'] == 'stevenhan']

In [6]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,...,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move
0,WGJV5DRb,1,white,stevenhan,c4,10+5,5,60003.0,600.03,-3.0,...,1,1,0,0,1,0,0,0,0,0
2,WGJV5DRb,2,white,stevenhan,Nc3,10+5,5,60179.0,601.79,-176.0,...,1,1,0,0,0,1,0,0,0,0
4,WGJV5DRb,3,white,stevenhan,g3,10+5,5,59891.0,598.91,288.0,...,1,1,0,0,1,0,0,0,0,0
6,WGJV5DRb,4,white,stevenhan,cxd5,10+5,5,59387.0,593.87,504.0,...,1,1,0,0,1,0,0,0,0,0
8,WGJV5DRb,5,white,stevenhan,d4,10+5,5,59763.0,597.63,-376.0,...,1,1,0,0,1,0,0,0,0,0

In [7]:
df.shape

(3358, 40)

In [8]:
df.columns

Index(['game_id', 'move_number', 'color', 'username', 'move', 'time_control',
       'increment_sec', 'time_left_cs', 'time_left_sec', 'time_spent_cs',
       'time_spent_sec', 'time_left_ratio', 'time_spent_ratio', 'eval', 'mate',
       'best_move', 'variation', 'judgment', 'eval_volatility',
       'pieces_remaining', 'material_density', 'num_minor_pieces', 'num_rooks',
       'num_queens', 'num_pawns', 'complexity_material_score',
       'white_castled_king', 'white_castled_queen', 'black_castled_king',
       'black_castled_queen', 'queen_present', 'is_opening', 'is_middlegame',
       'is_endgame', 'is_pawn_move', 'is_knight_move', 'is_bishop_move',
       'is_rook_move', 'is_queen_move', 'is_king_move'],
      dtype='str')

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
df[df['time_spent_sec'] < 0].sort_values('time_spent_sec', ascending = True)

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move
2736,qK5agCeH,62,white,stevenhan,Rf1,90+30,30,29687.0,296.87,-3004.0,-30.04,0.054976,-0.005563,0.0,NaN,NaN,NaN,NaN,0.000000,22,0.6875,1,4,1,14,46,1,0,0,0,1,0,1,0,0,0,0,1,0,0
2732,qK5agCeH,60,white,stevenhan,Rf1,90+30,30,23683.0,236.83,-3000.0,-30.00,0.043857,-0.005556,0.0,NaN,NaN,NaN,NaN,0.000000,22,0.6875,1,4,1,14,46,1,0,0,0,1,0,1,0,0,0,0,1,0,0
2734,qK5agCeH,61,white,stevenhan,Rb1,90+30,30,26683.0,266.83,-3000.0,-30.00,0.049413,-0.005556,0.0,NaN,NaN,NaN,NaN,0.000000,22,0.6875,1,4,1,14,46,1,0,0,0,1,0,1,0,0,0,0,1,0,0
2726,qK5agCeH,57,white,stevenhan,Bg4,90+30,30,18683.0,186.83,-3000.0,-30.00,0.034598,-0.005556,0.0,NaN,NaN,NaN,NaN,0.942809,22,0.6875,1,4,1,14,46,1,0,0,0,1,0,1,0,0,0,1,0,0,0
2616,qK5agCeH,2,white,stevenhan,Nc3,90+30,30,542811.0,5428.11,-2808.0,-28.08,1.005206,-0.005200,23.0,NaN,NaN,NaN,NaN,6.548961,32,1.0000,8,4,2,16,78,0,0,0,0,1,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,hX9m9UOi,1,white,stevenhan,c4,10+5,5,60003.0,600.03,-3.0,-0.03,1.000050,-0.000050,12.0,NaN,NaN,NaN,NaN,NaN,32,1.0000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
1738,WtHzLqnH,1,white,stevenhan,c4,10+5,5,60003.0,600.03,-3.0,-0.03,1.000050,-0.000050,12.0,NaN,NaN,NaN,NaN,NaN,32,1.0000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
866,mgNvP6Cf,1,black,stevenhan,e6,10+5,5,60003.0,600.03,-3.0,-0.03,1.000050,-0.000050,22.0,NaN,NaN,NaN,NaN,NaN,32,1.0000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
658,JwmDlPJF,1,black,stevenhan,e6,10+5,5,60003.0,600.03,-3.0,-0.03,1.000050,-0.000050,22.0,NaN,NaN,NaN,NaN,NaN,32,1.0000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
3146,wJaFBo5u,36,black,stevenhan,exf4,10+0,0,11613.0,116.13,-2.0,-0.02,0.193550,-0.000033,-550.0,NaN,NaN,NaN,NaN,62.829575,18,0.5625,2,2,2,10,44,1,0,1,0,1,0,1,0,1,0,0,0,0,0

In [11]:
# Remove negative time_spent and add the increment to it properly

# Move 1: zero out time_spent (no previous clock to diff against)
mask_first = df['move_number'] == 1
df.loc[mask_first, 'time_spent_cs'] = 0
df.loc[mask_first, 'time_spent_sec'] = 0

# All other moves: add increment back into time_spent
mask_rest = df['move_number'] != 1
df.loc[mask_rest, 'time_spent_sec'] = df.loc[mask_rest, 'time_spent_sec'] + df.loc[mask_rest, 'increment_sec']
df.loc[mask_rest, 'time_spent_cs'] = df.loc[mask_rest, 'time_spent_cs'] + df.loc[mask_rest, 'increment_sec'] * 100

In [12]:
df[df['time_spent_sec'] < 0].sort_values('time_spent_sec', ascending = True)

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move
160,WGJV5DRb,81,white,stevenhan,Kxg7,10+5,5,2651.0,26.51,-4.0,-0.04,0.044183,-0.008400,0.0,NaN,NaN,NaN,NaN,13.441230,8,0.25000,0,1,0,8,13,1,0,1,0,0,0,0,1,0,0,0,0,0,1
265,whq08Epc,46,black,stevenhan,Rxe3+,10+5,5,3523.0,35.23,-4.0,-0.04,0.058717,-0.008400,422.0,NaN,e6f6,Rf6 Ke4,Inaccuracy,64.675257,12,0.37500,1,0,0,12,15,1,0,1,0,0,0,0,1,0,0,0,1,0,0
277,whq08Epc,52,black,stevenhan,Kg3,10+5,5,5659.0,56.59,-4.0,-0.04,0.094317,-0.008400,1426.0,NaN,NaN,NaN,NaN,1594.096818,7,0.21875,1,0,0,7,10,1,0,1,0,0,0,0,1,0,0,0,0,0,1
283,whq08Epc,55,black,stevenhan,h3,10+5,5,6051.0,60.51,-4.0,-0.04,0.100850,-0.008400,2995.0,NaN,NaN,NaN,NaN,486.551813,6,0.18750,1,0,0,6,9,1,0,1,0,0,0,0,1,1,0,0,0,0,0
291,whq08Epc,59,black,stevenhan,Kxh1,10+5,5,7923.0,79.23,-4.0,-0.04,0.132050,-0.008400,605.0,NaN,NaN,NaN,NaN,3624.881822,4,0.12500,1,0,1,3,15,1,0,1,0,1,0,0,1,0,0,0,0,0,1
295,whq08Epc,61,black,stevenhan,Kf3,10+5,5,8923.0,89.23,-4.0,-0.04,0.148717,-0.008400,5043.0,NaN,g2f2,Kf2 Kc5 Ke3 a5 Ke2 Kd4 Kd2 a6 Ke2 Kd5 Kf2 Ke6,Inaccuracy,2091.624409,3,0.09375,1,0,1,2,14,1,0,1,0,1,0,0,1,0,0,0,0,0,1
299,whq08Epc,63,black,stevenhan,Kd5,10+5,5,9923.0,99.23,-4.0,-0.04,0.165383,-0.008400,NaN,13.0,e4d3,Kd3 Ka5 Ke4 a7 Ke5 Kb6 Kf5 Kb5 Kf6 Kc5 Ke5 Kc4,Inaccuracy,2380.000000,3,0.09375,1,0,1,2,14,1,0,1,0,1,0,0,1,0,0,0,0,0,1
303,whq08Epc,65,black,stevenhan,Kd7,10+5,5,10923.0,109.23,-4.0,-0.04,0.182050,-0.008400,NaN,5.0,NaN,NaN,NaN,NaN,3,0.09375,1,0,2,1,22,1,0,1,0,1,0,0,1,0,0,0,0,0,1
391,P8buBILB,12,black,stevenhan,Bxe4,10+5,5,47651.0,476.51,-4.0,-0.04,0.794183,-0.008400,2.0,NaN,NaN,NaN,NaN,4.784233,26,0.81250,4,4,2,14,64,1,0,1,0,1,0,1,0,0,0,1,0,0,0
405,P8buBILB,19,black,stevenhan,Rd8,10+5,5,42899.0,428.99,-4.0,-0.04,0.714983,-0.008400,0.0,NaN,NaN,NaN,NaN,6.164414,18,0.56250,2,0,1,14,29,1,0,1,0,1,0,0,1,0,0,0,1,0,0
439,P8buBILB,36,black,stevenhan,gxf5,10+5,5,16987.0,169.87,-4.0,-0.04,0.283117,-0.008400,0.0,NaN,NaN,NaN,NaN,0.000000,10,0.31250,0,0,1,9,18,1,0,1,0,1,0,0,1,1,0,0,0,0,0
477,P8buBILB,55,black,stevenhan,Bf4,10+5,5,1803.0,18.03,-4.0,-0.04,0.030050,-0.008400,0.0,NaN,NaN,NaN,NaN,0.000000,6,0.18750,0,0,2,5,23,1,0,1,0,1,0,0,1,0,0,1,0,0,0
610,qspbeK9s,24,white,stevenhan,Rxd4,10+5,5,31395.0,313.95,-4.0,-0.04,0.523250,-0.008400,5.0,NaN,NaN,NaN,NaN,7.542472,16,0.50000,3,3,0,9,33,1,0,1,0,0,0,0,1,0,0,0,1,0,0
800,hX9m9UOi,60,white,stevenhan,Kf3,10+5,5,2819.0,28.19,-4.0,-0.04,0.046983,-0.008400,0.0,NaN,NaN,NaN,NaN,0.000000,5,0.15625,0,0,1,9,18,1,0,1,0,1,0,0,1,0,0,0,0,0,1
1005,SHFG77Qy,43,white,stevenhan,Rc8,10+5,5,35587.0,355.87,-4.0,-0.04,0.593117,-0.008400,-938.0,NaN,NaN,NaN,NaN,108.435337,14,0.43750,4,0,0,11,23,1,0,1,0,0,0,0,1,0,0,0,1,0,0
1143,cqgbDBuk,26,black,stevenhan,Rxa8,10+5,5,32403.0,324.03,-4.0,-0.04,0.540050,-0.008400,-40.0,NaN,NaN,NaN,NaN,6.377042,17,0.53125,1,3,0,12,30,1,0,0,0,0,0,0,1,0,0,0,1,0,0
1247,cqgbDBuk,78,black,stevenhan,f5+,10+5,5,3979.0,39.79,-4.0,-0.04,0.066317,-0.008400,0.0,NaN,NaN,NaN,NaN,0.000000,4,0.12500,0,2,0,7,17,1,0,0,0,0,0,0,1,1,0,0,0,0,0
1316,SBDe3ek5,31,black,stevenhan,Rxe6,10+5,5,6579.0,65.79,-4.0,-0.04,0.109650,-0.008400,549.0,NaN,NaN,NaN,NaN,3.681787,16,0.50000,1,2,0,12,25,1,0,1,0,0,0,0,1,0,0,0,1,0,0
1322,SBDe3ek5,34,black,stevenhan,cxd3,10+5,5,7699.0,76.99,-4.0,-0.04,0.128317,-0.008400,541.0,NaN,NaN,NaN,NaN,3.299832,14,0.43750,1,1,0,11,19,1,0,1,0,0,0,0,1,1,0,0,0,0,0
1356,SBDe3ek5,51,black,stevenhan,Rf1+,10+5,5,11459.0,114.59,-4.0,-0.04,0.190983,-0.008400,1156.0,NaN,NaN,NaN,NaN,66.137903,8,0.25000,1,0,0,7,10,1,0,1,0,0,0,0,1,0,0,0,1,0,0
1495,APtuyYz1,61,black,stevenhan,Kd3,10+5,5,5219.0,52.19,-4.0,-0.04,0.086983,-0.008400,NaN,10.0,NaN,NaN,NaN,NaN,6,0.18750,0,0,0,8,8,1,0,1,0,0,0,0,1,0,0,0,0,0,1
1501,APtuyYz1,64,black,stevenhan,Kd4,10+5,5,6539.0,65.39,-4.0,-0.04,0.108983,-0.008400,NaN,7.0,NaN,NaN,NaN,NaN,6,0.18750,0,0,0,8,8,1,0,1,0,0,0,0,1,0,0,0,0,0,1
1543,cRaPOprh,21,white,stevenhan,dxe4,10+5,5,38667.0,386.67,-4.0,-0.04,0.644450,-0.008400,-321.0,NaN,NaN,NaN,NaN,5.715476,24,0.75000,4,3,2,13,58,1,0,1,0,1,0,1,0,1,0,0,0,0,0
1733,OlAdWpM6,40,white,stevenhan,Qxe6,10+5,5,19195.0,191.95,-4.0,-0.04,0.319917,-0.008400,NaN,8.0,NaN,NaN,NaN,NaN,24,0.75000,4,4,0,14,46,1,0,1,0,0,0,0,1,0,0,0,0,1,0
2192,7nC5Flxg,14,black,stevenhan,Bxc2,10+5,5,51747.0,517.47,-4.0,-0.04,0.862450,-0.008400,-123.0,NaN,NaN,NaN,NaN,3.741657,27,0.84375,6,4,0,16,54,1,0,1,0,0,0,0,1,0,0,1,0,0,0
2388,dnO12S1e,25,black,stevenhan,Kxd7,10+5,5,11411.0,114.11,-4.0,-0.04,0.190183,-0.008400,946.0,NaN,NaN,NaN,NaN,19.154344,14,0.43750,2,0,2,9,33,1,0,0,0,1,0,0,1,0,0,0,0,0,1
2459,3gJzIPyt,33,black,stevenhan,Nxe7,10+5,5,5715.0,57.15,-4.0,-0.04,0.095250,-0.008400,677.0,NaN,NaN,NaN,NaN,49.263464,20,0.62500,2,1,2,13,42,1,0,1,0,1,0,0,1,0,1,0,0,0,0
2491,3gJzIPyt,49,black,stevenhan,f4,10+5,5,8931.0,89.31,-4.0,-0.04,0.148850,-0.008400,NaN,8.0,NaN,NaN,NaN,NaN,10,0.31250,0,1,1,8,22,1,0,1,0,1,0,0,1,1,0,0,0,0,0
3598,sCAg0f9z,19,white,stevenhan,Rxf1,13+7,7,36419.0,364.19,-4.0,-0.04,0.466910,-0.009026,0.0,NaN,NaN,NaN,NaN,42.081931,28,0.87500,7,3,1,15,60,1,0,1,0,1,0,1,0,0,0,0,1,0,0
3447,9t5vhITN,16,black,stevenhan,Bxd4,10+1,1,35091.0,350.91,-4.0,-0.04,0.584850,-0.001733,-46.0,NaN,NaN,NaN,NaN,6.342099,22,0.68750,3,4,0,13,42,1,0,1,0,0,0,0,1,0,0,1,0,0,0
2736,qK5agCeH,62,white,stevenhan,Rf1,90+30,30,29687.0,296.87,-4.0,-0.04,0.054976,-0.005563,0.0,NaN,NaN,NaN,NaN,0.000000,22,0.68750,1,4,1,14,46,1,0,0,0,1,0,1,0,0,0,0,1,0,0
3146,wJaFBo5u,36,black,stevenhan,exf4,10+0,0,11613.0,116.13,-2.0,-0.02,0.193550,-0.000033,-550.0,NaN,NaN,NaN,NaN,62.829575,18,0.56250,2,2,2,10,44,1,0,1,0,1,0,1,0,1,0,0,0,0,0

In [13]:
# set these remaining to zero
df.loc[df['time_spent_cs'] < 0, 'time_spent_cs'] = 0
df.loc[df['time_spent_sec'] < 0, 'time_spent_sec'] = 0

In [14]:
df[df['time_spent_sec'] < 0].sort_values('time_spent_sec', ascending = True)

Empty DataFrame
Columns: [game_id, move_number, color, username, move, time_control, increment_sec, time_left_cs, time_left_sec, time_spent_cs, time_spent_sec, time_left_ratio, time_spent_ratio, eval, mate, best_move, variation, judgment, eval_volatility, pieces_remaining, material_density, num_minor_pieces, num_rooks, num_queens, num_pawns, complexity_material_score, white_castled_king, white_castled_queen, black_castled_king, black_castled_queen, queen_present, is_opening, is_middlegame, is_endgame, is_pawn_move, is_knight_move, is_bishop_move, is_rook_move, is_queen_move, is_king_move]
Index: []

In [15]:
df[df['time_left_cs'].isnull()]

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move
3807,R0VItgHE,1,white,stevenhan,d4,8+0,0,NaN,NaN,0.0,0.0,0.0,0.0,24.0,NaN,NaN,NaN,NaN,NaN,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
3809,R0VItgHE,2,white,stevenhan,c4,8+0,0,NaN,NaN,NaN,NaN,0.0,0.0,24.0,NaN,NaN,NaN,NaN,3.299832,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0
3811,R0VItgHE,3,white,stevenhan,cxd5,8+0,0,NaN,NaN,NaN,NaN,0.0,0.0,21.0,NaN,NaN,NaN,NaN,4.189935,31,0.96875,8,4,2,15,77,0,0,0,0,1,1,0,0,1,0,0,0,0,0
3813,R0VItgHE,4,white,stevenhan,e4,8+0,0,NaN,NaN,NaN,NaN,0.0,0.0,49.0,NaN,NaN,NaN,NaN,23.683093,30,0.93750,7,4,2,15,74,0,0,0,0,1,1,0,0,1,0,0,0,0,0
3815,R0VItgHE,5,white,stevenhan,Nc3,8+0,0,NaN,NaN,NaN,NaN,0.0,0.0,33.0,NaN,NaN,NaN,NaN,6.599663,30,0.93750,7,4,2,15,74,0,0,0,0,1,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6700,vKbIs1Ca,8,black,stevenhan,O-O,30+0,0,NaN,NaN,NaN,NaN,0.0,0.0,24.0,NaN,NaN,NaN,NaN,0.471405,32,1.00000,8,4,2,16,78,0,0,1,0,1,1,0,0,0,0,0,0,0,1
6702,vKbIs1Ca,9,black,stevenhan,Ne4,30+0,0,NaN,NaN,NaN,NaN,0.0,0.0,49.0,NaN,NaN,NaN,NaN,11.145502,32,1.00000,8,4,2,16,78,1,0,1,0,1,0,1,0,0,1,0,0,0,0
6704,vKbIs1Ca,10,black,stevenhan,Nxc3,30+0,0,NaN,NaN,NaN,NaN,0.0,0.0,139.0,NaN,d8e7,Qxe7 Rc1 b6 cxd5 exd5 Nxe4 dxe4 Nd2 Bb7 Qa4 f5...,Inaccuracy,45.519227,30,0.93750,6,4,2,16,72,1,0,1,0,1,0,1,0,0,1,0,0,0,0
6706,vKbIs1Ca,11,black,stevenhan,Nxd1,30+0,0,NaN,NaN,NaN,NaN,0.0,0.0,139.0,NaN,NaN,NaN,NaN,0.942809,28,0.87500,4,4,2,16,66,1,0,1,0,1,0,1,0,0,1,0,0,0,0
6708,vKbIs1Ca,12,black,stevenhan,Re8,30+0,0,NaN,NaN,NaN,NaN,0.0,0.0,317.0,NaN,d1b2,Nxb2 cxd5 exd5 Bxf8 Kxf8 a4 Nb6 a5 N6c4 Rfc1 f...,Mistake,81.019888,28,0.87500,4,4,2,16,66,1,0,1,0,1,0,1,0,0,0,0,1,0,0

In [ ]:
# drop the time_left_cs that is empty because the game data is too old and doesn't have data for that
df = df.dropna(subset=['time_left_cs'])

In [18]:
df[df['time_left_cs'].isnull()]

Empty DataFrame
Columns: [game_id, move_number, color, username, move, time_control, increment_sec, time_left_cs, time_left_sec, time_spent_cs, time_spent_sec, time_left_ratio, time_spent_ratio, eval, mate, best_move, variation, judgment, eval_volatility, pieces_remaining, material_density, num_minor_pieces, num_rooks, num_queens, num_pawns, complexity_material_score, white_castled_king, white_castled_queen, black_castled_king, black_castled_queen, queen_present, is_opening, is_middlegame, is_endgame, is_pawn_move, is_knight_move, is_bishop_move, is_rook_move, is_queen_move, is_king_move]
Index: []

In [19]:
df.groupby(['game_id','username'])['time_spent_sec'].mean()

game_id   username
04ELJhAC  stevenhan     19.461695
3gJzIPyt  stevenhan     14.243019
52ntHwYU  stevenhan     14.840435
71bu21I8  stevenhan      9.696000
7nC5Flxg  stevenhan     12.917714
9aF3VV33  stevenhan     24.430000
9t5vhITN  stevenhan     14.862258
APtuyYz1  stevenhan     13.276875
AZF9lqDz  stevenhan     12.500000
CGfnBZa5  stevenhan     18.428000
Eohxem4N  stevenhan     20.923929
IKceIQdM  stevenhan     12.631463
J0uMuZkY  stevenhan     19.449143
JwmDlPJF  stevenhan     16.190000
K32rUkvS  stevenhan     22.568387
MCy59q15  stevenhan     13.030652
MX2B8duE  stevenhan     11.144884
MZKDVf3t  stevenhan     29.930000
MxcC5ExJ  stevenhan     13.163488
OcMqzxCd  stevenhan      7.002857
OlAdWpM6  stevenhan     14.798333
P8buBILB  stevenhan     12.226486
SBDe3ek5  stevenhan     12.686780
SHFG77Qy  stevenhan     10.062400
UeQnVviQ  stevenhan      8.536800
WD9zWbUJ  stevenhan     13.161481
WGJV5DRb  stevenhan     11.737011
WtHzLqnH  stevenhan     15.223846
WyBuHGGG  stevenhan     33.071111
XbrpqKxk  stevenhan     16.138800
cRaPOprh  stevenhan     15.512941
cqgbDBuk  stevenhan     11.723827
dCFbbCtg  stevenhan     11.391538
dnO12S1e  stevenhan     24.662222
hX9m9UOi  stevenhan     13.676875
jghr11lo  stevenhan     17.765652
mgNvP6Cf  stevenhan     14.159286
not7T6Di  stevenhan     14.268070
qK5agCeH  stevenhan    111.825806
qspbeK9s  stevenhan     13.843696
sCAg0f9z  stevenhan     19.047619
wIoeTXID  stevenhan      9.630385
wJaFBo5u  stevenhan     13.442222
whq08Epc  stevenhan     12.595000
Name: time_spent_sec, dtype: float64

In [20]:
# Add average time spent per move per game
df['avg_time_spent_per_move'] = df.groupby(['game_id', 'username'])['time_spent_sec'].transform('mean')

In [21]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move
0,WGJV5DRb,1,white,stevenhan,c4,10+5,5,60003.0,600.03,0.0,0.00,1.000050,-0.000050,12.0,NaN,NaN,NaN,NaN,NaN,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
2,WGJV5DRb,2,white,stevenhan,Nc3,10+5,5,60179.0,601.79,324.0,3.24,1.002983,-0.002933,12.0,NaN,NaN,NaN,NaN,0.942809,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,0,1,0,0,0,0,11.737011
4,WGJV5DRb,3,white,stevenhan,g3,10+5,5,59891.0,598.91,788.0,7.88,0.998183,0.004800,-9.0,NaN,NaN,NaN,NaN,12.229291,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
6,WGJV5DRb,4,white,stevenhan,cxd5,10+5,5,59387.0,593.87,1004.0,10.04,0.989783,0.008400,-18.0,NaN,NaN,NaN,NaN,4.027682,31,0.96875,8,4,2,15,77,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
8,WGJV5DRb,5,white,stevenhan,d4,10+5,5,59763.0,597.63,124.0,1.24,0.996050,-0.006267,-25.0,NaN,NaN,NaN,NaN,4.921608,30,0.93750,8,4,2,14,76,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011

In [22]:
# Recalcualted the new column: Calculate how much longer/shorter this move was compared to average
df['time_spent_ratio'] = df['time_spent_sec'] / df['avg_time_spent_per_move']

In [23]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move
0,WGJV5DRb,1,white,stevenhan,c4,10+5,5,60003.0,600.03,0.0,0.00,1.000050,0.000000,12.0,NaN,NaN,NaN,NaN,NaN,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
2,WGJV5DRb,2,white,stevenhan,Nc3,10+5,5,60179.0,601.79,324.0,3.24,1.002983,0.276050,12.0,NaN,NaN,NaN,NaN,0.942809,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,0,1,0,0,0,0,11.737011
4,WGJV5DRb,3,white,stevenhan,g3,10+5,5,59891.0,598.91,788.0,7.88,0.998183,0.671380,-9.0,NaN,NaN,NaN,NaN,12.229291,32,1.00000,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
6,WGJV5DRb,4,white,stevenhan,cxd5,10+5,5,59387.0,593.87,1004.0,10.04,0.989783,0.855414,-18.0,NaN,NaN,NaN,NaN,4.027682,31,0.96875,8,4,2,15,77,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011
8,WGJV5DRb,5,white,stevenhan,d4,10+5,5,59763.0,597.63,124.0,1.24,0.996050,0.105649,-25.0,NaN,NaN,NaN,NaN,4.921608,30,0.93750,8,4,2,14,76,0,0,0,0,1,1,0,0,1,0,0,0,0,0,11.737011

In [ ]:
def process_game_evals(group):
    group = group.sort_values('move_number').copy()
    
    group['is_mate_threat'] = ((group['mate'].notna()) & (group['mate'] != 0)).astype(int)
    group['is_checkmate'] = (group['eval'].isna() & group['mate'].isna()).astype(int)
    
    group['prev_eval'] = group['eval'].shift(1)
    group['eval_change'] = group['eval'] - group['prev_eval']
    
    eval_loss = []
    for idx, row in group.iterrows():
        if pd.isna(row['eval_change']):
            eval_loss.append(None)
        else:
            loss = -row['eval_change'] if row['color'] == 'white' else row['eval_change']
            eval_loss.append(max(0, loss))
    
    group['eval_loss'] = eval_loss
    return group

results = []
for game_id, group in df.groupby('game_id'):
    results.append(process_game_evals(group))

df = pd.concat(results).reset_index(drop=True)

In [25]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move,is_mate_threat,is_checkmate,prev_eval,eval_change,eval_loss
0,04ELJhAC,1,black,stevenhan,d5,10+10,10,60003.0,600.03,0.0,0.00,1.000050,0.000000,32.0,NaN,NaN,NaN,NaN,NaN,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,19.461695,0,0,NaN,NaN,NaN
1,04ELJhAC,2,black,stevenhan,c6,10+10,10,58795.0,587.95,2208.0,22.08,0.979917,1.134536,23.0,NaN,NaN,NaN,NaN,18.517259,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,19.461695,0,0,32.0,-9.0,0.0
2,04ELJhAC,3,black,stevenhan,Nf6,10+10,10,59267.0,592.67,528.0,5.28,0.987783,0.271302,17.0,NaN,NaN,NaN,NaN,4.109609,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,0,1,0,0,0,0,19.461695,0,0,23.0,-6.0,0.0
3,04ELJhAC,4,black,stevenhan,Bg4,10+10,10,59731.0,597.31,536.0,5.36,0.995517,0.275413,24.0,NaN,NaN,NaN,NaN,3.858612,32,1.0,8,4,2,16,78,1,0,0,0,1,1,0,0,0,0,1,0,0,0,19.461695,0,0,17.0,7.0,7.0
4,04ELJhAC,5,black,stevenhan,Nbd7,10+10,10,60563.0,605.63,168.0,1.68,1.009383,0.086323,16.0,NaN,NaN,NaN,NaN,3.299832,32,1.0,8,4,2,16,78,1,0,0,0,1,1,0,0,0,1,0,0,0,0,19.461695,0,0,24.0,-8.0,0.0

In [ ]:
# Create binary error columns based on eval loss (in centipawns)
df['is_inaccuracy'] = ((df['eval_loss'] >= 100) & (df['eval_loss'] < 200)).astype(int)
df['is_mistake'] = ((df['eval_loss'] >= 200) & (df['eval_loss'] < 300)).astype(int)
df['is_blunder'] = (df['eval_loss'] >= 300).astype(int)

In [27]:
# apply a unified eval column to combine mate and eval info into one column

max_eval = df['eval'].max()
min_eval = df['eval'].min()
max_white_mate = df['mate'].max()   # most positive (e.g. 31)
max_black_mate = df['mate'].min()   # most negative (e.g. -26)

FLOOR_BUFFER = 300
WHITE_CAP_BUFFER = max_eval * 0.10
BLACK_CAP_BUFFER = abs(min_eval) * 0.10

WHITE_CAP   = max_eval + WHITE_CAP_BUFFER
WHITE_FLOOR = max_eval + FLOOR_BUFFER
BLACK_CAP   = min_eval - BLACK_CAP_BUFFER
BLACK_FLOOR = min_eval - FLOOR_BUFFER

print(f"Eval range:       {min_eval} to {max_eval}")
print(f"Mate range:       {max_black_mate} to {max_white_mate}")
print(f"White cap buffer: {WHITE_CAP_BUFFER:.0f} (10% of {max_eval})")
print(f"Black cap buffer: {BLACK_CAP_BUFFER:.0f} (10% of {abs(min_eval)})")
print(f"White mate band:  {WHITE_FLOOR:.0f} (mate in {max_white_mate}) → {WHITE_CAP:.0f} (mate in 1)")
print(f"Black mate band:  {BLACK_FLOOR:.0f} (mate in {max_black_mate}) → {BLACK_CAP:.0f} (mate in -1)")

def unified_eval(row):
    if row['is_checkmate']:
        return WHITE_CAP if row['color'] == 'white' else BLACK_CAP

    elif row['is_mate_threat']:
        m = row['mate']
        if m > 0:  # white has forced mate
            proxy = WHITE_CAP - (m - 1) * (WHITE_CAP - WHITE_FLOOR) / (max_white_mate - 1)
        else:      # black has forced mate
            proxy = BLACK_CAP + (abs(m) - 1) * (abs(BLACK_CAP) - abs(BLACK_FLOOR)) / (abs(max_black_mate) - 1)
        return proxy

    else:
        return row['eval']

df['eval_unified'] = df.apply(unified_eval, axis=1)

Eval range:       -5141.0 to 8308.0
Mate range:       -18.0 to 28.0
White cap buffer: 831 (10% of 8308.0)
Black cap buffer: 514 (10% of 5141.0)
White mate band:  8608 (mate in 28.0) → 9139 (mate in 1)
Black mate band:  -5441 (mate in -18.0) → -5655 (mate in -1)

In [28]:
df.head()

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move,is_mate_threat,is_checkmate,prev_eval,eval_change,eval_loss,is_inaccuracy,is_mistake,is_blunder,eval_unified
0,04ELJhAC,1,black,stevenhan,d5,10+10,10,60003.0,600.03,0.0,0.00,1.000050,0.000000,32.0,NaN,NaN,NaN,NaN,NaN,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,19.461695,0,0,NaN,NaN,NaN,0,0,0,32.0
1,04ELJhAC,2,black,stevenhan,c6,10+10,10,58795.0,587.95,2208.0,22.08,0.979917,1.134536,23.0,NaN,NaN,NaN,NaN,18.517259,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,1,0,0,0,0,0,19.461695,0,0,32.0,-9.0,0.0,0,0,0,23.0
2,04ELJhAC,3,black,stevenhan,Nf6,10+10,10,59267.0,592.67,528.0,5.28,0.987783,0.271302,17.0,NaN,NaN,NaN,NaN,4.109609,32,1.0,8,4,2,16,78,0,0,0,0,1,1,0,0,0,1,0,0,0,0,19.461695,0,0,23.0,-6.0,0.0,0,0,0,17.0
3,04ELJhAC,4,black,stevenhan,Bg4,10+10,10,59731.0,597.31,536.0,5.36,0.995517,0.275413,24.0,NaN,NaN,NaN,NaN,3.858612,32,1.0,8,4,2,16,78,1,0,0,0,1,1,0,0,0,0,1,0,0,0,19.461695,0,0,17.0,7.0,7.0,0,0,0,24.0
4,04ELJhAC,5,black,stevenhan,Nbd7,10+10,10,60563.0,605.63,168.0,1.68,1.009383,0.086323,16.0,NaN,NaN,NaN,NaN,3.299832,32,1.0,8,4,2,16,78,1,0,0,0,1,1,0,0,0,1,0,0,0,0,19.461695,0,0,24.0,-8.0,0.0,0,0,0,16.0

In [29]:
df[df['time_spent_sec'].isnull()]

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move,is_mate_threat,is_checkmate,prev_eval,eval_change,eval_loss,is_inaccuracy,is_mistake,is_blunder,eval_unified
340,AZF9lqDz,28,black,stevenhan,Rxc8,10+0,0,4555.0,45.55,0.0,NaN,0.075917,NaN,130.0,NaN,NaN,NaN,NaN,189.290488,15,0.46875,6,0,0,10,28,1,0,1,0,0,0,0,1,0,0,0,1,0,0,12.500000,0,0,535.0,-405.0,0.0,0,0,0,130.0
358,AZF9lqDz,46,black,stevenhan,Kxg6,10+0,0,498.0,4.98,0.0,NaN,0.008300,NaN,466.0,NaN,NaN,NaN,NaN,7.118052,11,0.34375,5,0,0,8,23,1,0,1,0,0,0,0,1,0,0,0,0,0,1,12.500000,0,0,482.0,-16.0,0.0,0,0,0,466.0
360,AZF9lqDz,48,black,stevenhan,Kxh5,10+0,0,256.0,2.56,0.0,NaN,0.004267,NaN,474.0,NaN,NaN,NaN,NaN,4.966555,9,0.28125,5,0,0,6,21,1,0,1,0,0,0,0,1,0,0,0,0,0,1,12.500000,0,0,485.0,-11.0,0.0,0,0,0,474.0
514,K32rUkvS,10,white,stevenhan,h3,10+5,5,61579.0,615.79,500.0,NaN,1.026317,NaN,34.0,NaN,NaN,NaN,NaN,4.966555,32,1.00000,8,4,2,16,78,1,0,1,0,1,0,1,0,1,0,0,0,0,0,22.568387,0,0,23.0,11.0,0.0,0,0,0,34.0
553,MCy59q15,17,white,stevenhan,Rxd1,10+0,0,26707.0,267.07,0.0,NaN,0.445117,NaN,-22.0,NaN,NaN,NaN,NaN,1.699673,24,0.75000,4,3,1,14,50,1,0,1,0,1,0,1,0,0,0,0,1,0,0,13.030652,0,0,-21.0,-1.0,1.0,0,0,0,-22.0
582,MCy59q15,46,white,stevenhan,f5,10+0,0,184.0,1.84,0.0,NaN,0.003067,NaN,-560.0,NaN,NaN,NaN,NaN,5.354126,13,0.40625,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-552.0,-8.0,8.0,0,0,0,-560.0
585,MCy59q15,49,white,stevenhan,g5,10+0,0,62.0,0.62,0.0,NaN,0.001033,NaN,-618.0,NaN,NaN,NaN,NaN,7.483315,12,0.37500,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-606.0,-12.0,12.0,0,0,0,-618.0
586,MCy59q15,50,white,stevenhan,f6+,10+0,0,62.0,0.62,0.0,NaN,0.001033,NaN,-700.0,NaN,NaN,NaN,NaN,45.382326,12,0.37500,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-618.0,-82.0,82.0,0,0,0,-700.0
587,MCy59q15,51,white,stevenhan,gxf6+,10+0,0,62.0,0.62,0.0,NaN,0.001033,NaN,-696.0,NaN,NaN,NaN,NaN,10.033278,10,0.31250,1,0,1,10,22,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-700.0,4.0,0.0,0,0,0,-696.0
605,MX2B8duE,18,black,stevenhan,axb6,10+0,0,45731.0,457.31,0.0,NaN,0.762183,NaN,445.0,NaN,NaN,NaN,NaN,27.604347,23,0.71875,3,4,2,12,59,1,0,1,0,1,0,1,0,1,0,0,0,0,0,11.144884,0,0,502.0,-57.0,0.0,0,0,0,445.0
625,MX2B8duE,38,black,stevenhan,Bxc3,10+0,0,13619.0,136.19,0.0,NaN,0.226983,NaN,-555.0,NaN,NaN,NaN,NaN,9.568467,10,0.31250,0,0,2,8,26,1,0,1,0,1,0,0,1,0,0,1,0,0,0,11.144884,0,0,-559.0,4.0,4.0,0,0,0,-555.0
630,MX2B8duE,43,black,stevenhan,d1=Q,10+0,0,12499.0,124.99,0.0,NaN,0.208317,NaN,-120.0,NaN,NaN,NaN,NaN,6.649979,9,0.28125,0,0,4,5,41,1,0,1,0,1,0,0,1,1,0,0,0,0,0,11.144884,0,0,-107.0,-13.0,0.0,0,0,0,-120.0
633,MX2B8duE,46,black,stevenhan,Kxe2,10+0,0,12163.0,121.63,0.0,NaN,0.202717,NaN,-1088.0,NaN,NaN,NaN,NaN,86.426591,6,0.18750,0,0,2,4,22,1,0,1,0,1,0,0,1,0,0,0,0,0,1,11.144884,0,0,-884.0,-204.0,0.0,0,0,0,-1088.0
1002,WD9zWbUJ,10,black,stevenhan,exf4,10+0,0,50387.0,503.87,0.0,NaN,0.839783,NaN,57.0,NaN,NaN,NaN,NaN,3.399346,30,0.93750,8,4,2,14,76,1,0,1,0,1,0,1,0,1,0,0,0,0,0,13.161481,0,0,63.0,-6.0,0.0,0,0,0,57.0
1700,qspbeK9s,38,white,stevenhan,b4,10+5,5,16939.0,169.39,500.0,NaN,0.282317,NaN,431.0,NaN,NaN,NaN,NaN,30.444850,13,0.40625,3,0,0,9,18,1,0,1,0,0,0,0,1,1,0,0,0,0,0,13.843696,0,0,372.0,59.0,0.0,0,0,0,431.0
1795,wIoeTXID,23,white,stevenhan,Rfxe1,10+0,0,38907.0,389.07,0.0,NaN,0.648450,NaN,30.0,NaN,NaN,NaN,NaN,17.720045,20,0.62500,3,3,0,12,36,1,0,1,0,0,0,0,1,0,0,0,1,0,0,9.630385,0,0,66.0,-36.0,36.0,0,0,0,30.0
1852,whq08Epc,17,black,stevenhan,Bxc5,10+5,5,37059.0,370.59,500.0,NaN,0.617650,NaN,31.0,NaN,NaN,NaN,NaN,2.867442,20,0.62500,2,3,0,14,35,1,0,1,0,0,0,0,1,0,0,1,0,0,0,12.595000,0,0,28.0,3.0,3.0,0,0,0,31.0

In [30]:
mask = df['time_spent_sec'].isnull()
df.loc[mask, 'time_spent_sec'] = df.loc[mask, 'time_spent_cs'] / 100

In [31]:
df[df['time_spent_sec'].isnull()]

Empty DataFrame
Columns: [game_id, move_number, color, username, move, time_control, increment_sec, time_left_cs, time_left_sec, time_spent_cs, time_spent_sec, time_left_ratio, time_spent_ratio, eval, mate, best_move, variation, judgment, eval_volatility, pieces_remaining, material_density, num_minor_pieces, num_rooks, num_queens, num_pawns, complexity_material_score, white_castled_king, white_castled_queen, black_castled_king, black_castled_queen, queen_present, is_opening, is_middlegame, is_endgame, is_pawn_move, is_knight_move, is_bishop_move, is_rook_move, is_queen_move, is_king_move, avg_time_spent_per_move, is_mate_threat, is_checkmate, prev_eval, eval_change, eval_loss, is_inaccuracy, is_mistake, is_blunder, eval_unified]
Index: []

In [32]:
df[df['time_spent_ratio'].isnull()]

,game_id,move_number,color,username,move,time_control,increment_sec,time_left_cs,time_left_sec,time_spent_cs,time_spent_sec,time_left_ratio,time_spent_ratio,eval,mate,best_move,variation,judgment,eval_volatility,pieces_remaining,material_density,num_minor_pieces,num_rooks,num_queens,num_pawns,complexity_material_score,white_castled_king,white_castled_queen,black_castled_king,black_castled_queen,queen_present,is_opening,is_middlegame,is_endgame,is_pawn_move,is_knight_move,is_bishop_move,is_rook_move,is_queen_move,is_king_move,avg_time_spent_per_move,is_mate_threat,is_checkmate,prev_eval,eval_change,eval_loss,is_inaccuracy,is_mistake,is_blunder,eval_unified
340,AZF9lqDz,28,black,stevenhan,Rxc8,10+0,0,4555.0,45.55,0.0,0.0,0.075917,NaN,130.0,NaN,NaN,NaN,NaN,189.290488,15,0.46875,6,0,0,10,28,1,0,1,0,0,0,0,1,0,0,0,1,0,0,12.500000,0,0,535.0,-405.0,0.0,0,0,0,130.0
358,AZF9lqDz,46,black,stevenhan,Kxg6,10+0,0,498.0,4.98,0.0,0.0,0.008300,NaN,466.0,NaN,NaN,NaN,NaN,7.118052,11,0.34375,5,0,0,8,23,1,0,1,0,0,0,0,1,0,0,0,0,0,1,12.500000,0,0,482.0,-16.0,0.0,0,0,0,466.0
360,AZF9lqDz,48,black,stevenhan,Kxh5,10+0,0,256.0,2.56,0.0,0.0,0.004267,NaN,474.0,NaN,NaN,NaN,NaN,4.966555,9,0.28125,5,0,0,6,21,1,0,1,0,0,0,0,1,0,0,0,0,0,1,12.500000,0,0,485.0,-11.0,0.0,0,0,0,474.0
514,K32rUkvS,10,white,stevenhan,h3,10+5,5,61579.0,615.79,500.0,5.0,1.026317,NaN,34.0,NaN,NaN,NaN,NaN,4.966555,32,1.00000,8,4,2,16,78,1,0,1,0,1,0,1,0,1,0,0,0,0,0,22.568387,0,0,23.0,11.0,0.0,0,0,0,34.0
553,MCy59q15,17,white,stevenhan,Rxd1,10+0,0,26707.0,267.07,0.0,0.0,0.445117,NaN,-22.0,NaN,NaN,NaN,NaN,1.699673,24,0.75000,4,3,1,14,50,1,0,1,0,1,0,1,0,0,0,0,1,0,0,13.030652,0,0,-21.0,-1.0,1.0,0,0,0,-22.0
582,MCy59q15,46,white,stevenhan,f5,10+0,0,184.0,1.84,0.0,0.0,0.003067,NaN,-560.0,NaN,NaN,NaN,NaN,5.354126,13,0.40625,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-552.0,-8.0,8.0,0,0,0,-560.0
585,MCy59q15,49,white,stevenhan,g5,10+0,0,62.0,0.62,0.0,0.0,0.001033,NaN,-618.0,NaN,NaN,NaN,NaN,7.483315,12,0.37500,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-606.0,-12.0,12.0,0,0,0,-618.0
586,MCy59q15,50,white,stevenhan,f6+,10+0,0,62.0,0.62,0.0,0.0,0.001033,NaN,-700.0,NaN,NaN,NaN,NaN,45.382326,12,0.37500,1,0,1,12,24,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-618.0,-82.0,82.0,0,0,0,-700.0
587,MCy59q15,51,white,stevenhan,gxf6+,10+0,0,62.0,0.62,0.0,0.0,0.001033,NaN,-696.0,NaN,NaN,NaN,NaN,10.033278,10,0.31250,1,0,1,10,22,1,0,1,0,1,0,0,1,1,0,0,0,0,0,13.030652,0,0,-700.0,4.0,0.0,0,0,0,-696.0
605,MX2B8duE,18,black,stevenhan,axb6,10+0,0,45731.0,457.31,0.0,0.0,0.762183,NaN,445.0,NaN,NaN,NaN,NaN,27.604347,23,0.71875,3,4,2,12,59,1,0,1,0,1,0,1,0,1,0,0,0,0,0,11.144884,0,0,502.0,-57.0,0.0,0,0,0,445.0
625,MX2B8duE,38,black,stevenhan,Bxc3,10+0,0,13619.0,136.19,0.0,0.0,0.226983,NaN,-555.0,NaN,NaN,NaN,NaN,9.568467,10,0.31250,0,0,2,8,26,1,0,1,0,1,0,0,1,0,0,1,0,0,0,11.144884,0,0,-559.0,4.0,4.0,0,0,0,-555.0
630,MX2B8duE,43,black,stevenhan,d1=Q,10+0,0,12499.0,124.99,0.0,0.0,0.208317,NaN,-120.0,NaN,NaN,NaN,NaN,6.649979,9,0.28125,0,0,4,5,41,1,0,1,0,1,0,0,1,1,0,0,0,0,0,11.144884,0,0,-107.0,-13.0,0.0,0,0,0,-120.0
633,MX2B8duE,46,black,stevenhan,Kxe2,10+0,0,12163.0,121.63,0.0,0.0,0.202717,NaN,-1088.0,NaN,NaN,NaN,NaN,86.426591,6,0.18750,0,0,2,4,22,1,0,1,0,1,0,0,1,0,0,0,0,0,1,11.144884,0,0,-884.0,-204.0,0.0,0,0,0,-1088.0
1002,WD9zWbUJ,10,black,stevenhan,exf4,10+0,0,50387.0,503.87,0.0,0.0,0.839783,NaN,57.0,NaN,NaN,NaN,NaN,3.399346,30,0.93750,8,4,2,14,76,1,0,1,0,1,0,1,0,1,0,0,0,0,0,13.161481,0,0,63.0,-6.0,0.0,0,0,0,57.0
1700,qspbeK9s,38,white,stevenhan,b4,10+5,5,16939.0,169.39,500.0,5.0,0.282317,NaN,431.0,NaN,NaN,NaN,NaN,30.444850,13,0.40625,3,0,0,9,18,1,0,1,0,0,0,0,1,1,0,0,0,0,0,13.843696,0,0,372.0,59.0,0.0,0,0,0,431.0
1795,wIoeTXID,23,white,stevenhan,Rfxe1,10+0,0,38907.0,389.07,0.0,0.0,0.648450,NaN,30.0,NaN,NaN,NaN,NaN,17.720045,20,0.62500,3,3,0,12,36,1,0,1,0,0,0,0,1,0,0,0,1,0,0,9.630385,0,0,66.0,-36.0,36.0,0,0,0,30.0
1852,whq08Epc,17,black,stevenhan,Bxc5,10+5,5,37059.0,370.59,500.0,5.0,0.617650,NaN,31.0,NaN,NaN,NaN,NaN,2.867442,20,0.62500,2,3,0,14,35,1,0,1,0,0,0,0,1,0,0,1,0,0,0,12.595000,0,0,28.0,3.0,3.0,0,0,0,31.0

In [33]:
# Replace the blank values with 0
df['time_spent_ratio'] = df['time_spent_ratio'].fillna(0)

In [34]:
df[df['time_spent_ratio'].isnull()]

Empty DataFrame
Columns: [game_id, move_number, color, username, move, time_control, increment_sec, time_left_cs, time_left_sec, time_spent_cs, time_spent_sec, time_left_ratio, time_spent_ratio, eval, mate, best_move, variation, judgment, eval_volatility, pieces_remaining, material_density, num_minor_pieces, num_rooks, num_queens, num_pawns, complexity_material_score, white_castled_king, white_castled_queen, black_castled_king, black_castled_queen, queen_present, is_opening, is_middlegame, is_endgame, is_pawn_move, is_knight_move, is_bishop_move, is_rook_move, is_queen_move, is_king_move, avg_time_spent_per_move, is_mate_threat, is_checkmate, prev_eval, eval_change, eval_loss, is_inaccuracy, is_mistake, is_blunder, eval_unified]
Index: []

In [35]:
#recalcualte eval_volatility

df = df.sort_values(['game_id', 'move_number']).reset_index(drop=True)

def calc_eval_volatility(group):
    evals = group['eval_unified'].tolist()
    volatility = [None] * len(evals)
    for i in range(len(evals)):
        if i >= 2:
            recent = [evals[j] for j in range(max(0, i-2), i+1) if evals[j] is not None]
            if len(recent) >= 2:
                volatility[i] = np.std(recent)
    return pd.Series(volatility, index=group.index)

results = []
for game_id, group in df.groupby('game_id'):
    results.append(calc_eval_volatility(group))

df['eval_volatility'] = pd.concat(results).sort_index()

In [36]:
df.columns

Index(['game_id', 'move_number', 'color', 'username', 'move', 'time_control',
       'increment_sec', 'time_left_cs', 'time_left_sec', 'time_spent_cs',
       'time_spent_sec', 'time_left_ratio', 'time_spent_ratio', 'eval', 'mate',
       'best_move', 'variation', 'judgment', 'eval_volatility',
       'pieces_remaining', 'material_density', 'num_minor_pieces', 'num_rooks',
       'num_queens', 'num_pawns', 'complexity_material_score',
       'white_castled_king', 'white_castled_queen', 'black_castled_king',
       'black_castled_queen', 'queen_present', 'is_opening', 'is_middlegame',
       'is_endgame', 'is_pawn_move', 'is_knight_move', 'is_bishop_move',
       'is_rook_move', 'is_queen_move', 'is_king_move',
       'avg_time_spent_per_move', 'is_mate_threat', 'is_checkmate',
       'prev_eval', 'eval_change', 'eval_loss', 'is_inaccuracy', 'is_mistake',
       'is_blunder', 'eval_unified'],
      dtype='str')

In [ ]:


# Eval volatility (normalize to 0-1)
df['eval_volatility_norm'] = df['eval_volatility'].fillna(0)
max_vol = df['eval_volatility_norm'].quantile(0.95)
if max_vol > 0:
    df['eval_volatility_norm'] = (df['eval_volatility_norm'] / max_vol).clip(0, 1)

# Time pressure (0-1 scale, higher = more pressure)
df['time_pressure_norm'] = (1 - df['time_left_ratio']).clip(0, 1)

# Normalize complexity score to 0-1 before interacting
max_complexity = df['complexity_material_score'].quantile(0.95)  # robust to outliers
df['complexity_material_norm'] = (df['complexity_material_score'] / max_complexity).clip(0, 1)

# Now interact on equal footing
df['material_time_pressure_int'] = df['complexity_material_norm'] * df['time_pressure_norm']


# Additional interaction: time pressure × volatility
df['time_eval_volatility_int'] = df['time_pressure_norm'] * df['eval_volatility_norm']

In [ ]:
# Move number normalized within game — captures "late game fatigue"
# without depending on absolute move counts across different games
df['move_number_norm'] = df.groupby('game_id')['move_number'].transform(
    lambda x: (x - x.min()) / (x.max() - x.min() + 1)
)

In [ ]:
# Accumulated time pressure — are you consistently low on time,
# or did you just spend a lot on this one move?
df['cumulative_time_pressure'] = df.groupby(['game_id', 'color'])['time_spent_ratio'].transform(
    lambda x: x.expanding().mean()
)

In [ ]:
# Late game × endgame — move fatigue in technically demanding endgames
df['late_endgame_int'] = df['move_number_norm'] * df['is_endgame']

In [41]:
df.columns

Index(['game_id', 'move_number', 'color', 'username', 'move', 'time_control',
       'increment_sec', 'time_left_cs', 'time_left_sec', 'time_spent_cs',
       'time_spent_sec', 'time_left_ratio', 'time_spent_ratio', 'eval', 'mate',
       'best_move', 'variation', 'judgment', 'eval_volatility',
       'pieces_remaining', 'material_density', 'num_minor_pieces', 'num_rooks',
       'num_queens', 'num_pawns', 'complexity_material_score',
       'white_castled_king', 'white_castled_queen', 'black_castled_king',
       'black_castled_queen', 'queen_present', 'is_opening', 'is_middlegame',
       'is_endgame', 'is_pawn_move', 'is_knight_move', 'is_bishop_move',
       'is_rook_move', 'is_queen_move', 'is_king_move',
       'avg_time_spent_per_move', 'is_mate_threat', 'is_checkmate',
       'prev_eval', 'eval_change', 'eval_loss', 'is_inaccuracy', 'is_mistake',
       'is_blunder', 'eval_unified', 'eval_volatility_norm',
       'time_pressure_norm', 'complexity_material_norm',
       'material_time_pressure_int', 'time_eval_volatility_int',
       'move_number_norm', 'cumulative_time_pressure', 'late_endgame_int'],
      dtype='str')

In [42]:
df.to_csv('data/stevenhan_with_features.csv', index = False)